version: '3.7'

services:
  web:
    build: ./kvartirka
    env_file:
     - .env
    volumes:
      - static_volume:/app/static/
      - media_volume:/app/media/
    depends_on:
      - db
  db:
    image: postgres:13
    env_file: 
      - .env
    environment:
      - LANG:'ru_RU.UTF-8'
      - LANGUAGE:'ru_RU.UTF-8'
      - LC_ALL:'ru_RU.UTF-8'
    volumes:
      - ./postgres/init.sh:/docker-entrypoint-initdb.d/init.sh
      - db-data:/var/lib/postgresql/data
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - static_volume:/var/app/static/
      - media_volume:/var/app/media/
    ports:
    - 80:80
    depends_on:
    - web
volumes:
  static_volume:
  db-data:
  media_volume: