# Generated by Django 3.2.6 on 2021-08-05 20:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=255, unique=True)),
                ('depth', models.PositiveIntegerField()),
                ('numchild', models.PositiveIntegerField(default=0)),
                ('content', models.TextField()),
                ('create_datetime', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='create datetime')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tree_comments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['create_datetime'],
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('create_datetime', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='create datetime')),
                ('update_datetime', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='update datetime')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to=settings.AUTH_USER_MODEL)),
                ('root_comment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='api.comment')),
            ],
            options={
                'ordering': ['-create_datetime'],
            },
        ),
        migrations.AddField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tree_comments', to='api.post'),
        ),
    ]
