# Generated by Django 3.2.6 on 2021-08-27 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=255, unique=True)),
                ('depth', models.PositiveIntegerField()),
                ('numchild', models.PositiveIntegerField(default=0)),
                ('content', models.TextField()),
                ('create_datetime', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='create datetime')),
            ],
            options={
                'ordering': ['create_datetime'],
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('create_datetime', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='create datetime')),
                ('update_datetime', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='update datetime')),
            ],
            options={
                'ordering': ['-create_datetime'],
            },
        ),
    ]
